### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by simonjefford** [simonjefford/protodemo#1]
- [x] Finish the server
- [x] ASP.NET app - simple form that sends messages to the server
- [ ] ASP app - same as above
